# Generated by Django 4.2.1 on 2023-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            field=models.BigIntegerField(verbose_name="telefone"),
        ),
    ]
